### ISSUE TITLE
Wrong selector beautiful soup

### ISSUE THREAD

**Issue by general03** [danieliu/play-scraper#44] opened 2019-04-23 14:49 UTC
**Describe the bug**
The scraper crash because selector css not found

**To Reproduce**
` play_scraper.details('whatever_id')`
>> 'NoneType' object has no attribute 'attrs'

**Expected behavior**
No crash when selector not found

**Desktop**
 - OS: Win 7
 - Python Version 3.7
 - play_scraper Version 0.5.4

The issue is on utils.py line 241
`soup.select_one('.dQrBL img.ujDFqe')`

**Comment by danieliu** [comment] 2019-05-11 17:05
Duplicate of #42.

**Comment by danieliu** [comment] 2019-05-11 17:24
Fixed by #43

**Closed by danieliu** 2019-05-11 17:24 UTC
Labels: bug
