### ISSUE TITLE
'NoneType' object has no attribute 'attrs'

### ISSUE THREAD

**Issue by kushalkrip** [danieliu/play-scraper#48] opened 2019-05-09 09:11 UTC
It gives an error on line 240, 
`icon = (soup.select_one('.dQrBL img.ujDFqe')`
On replacing it with : `icon = (soup.select_one ('. XSyT2c `img.T75of')` as suggested in Issue 42, the error was still not resolved.
Kindly suggest on what should be done to resolve this issue.
--

**Comment by danieliu** [comment] 2019-05-11 17:07
Duplicate of #42

**Comment by danieliu** [comment] 2019-05-11 17:25
Fixed by #43

**Closed by danieliu** 2019-05-11 17:25 UTC
Labels: bug
