### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'attrs'

### ISSUE THREAD

**Issue by destrat18** [danieliu/play-scraper#47] opened 2019-05-05 10:24 UTC
`  File "/home/huma/humascraper/HumaScraper/spiders/store/store.py", line 229, in processGooglePlay
    data = android.fetchFromGooglePlay(self.fakeName if self.fakeName else response.meta["packageName"])
  File "/home/huma/humascraper/HumaScraper/common/util/android.py", line 243, in fetchFromGooglePlay
    gplay_info = play_scraper.details(package_name)
  File "/home/huma/humascraper/.env/lib/python3.5/site-packages/play_scraper/api.py", line 22, in details
    return s.details(app_id)
  File "/home/huma/humascraper/.env/lib/python3.5/site-packages/play_scraper/scraper.py", line 83, in details
    app_json = parse_app_details(soup)
  File "/home/huma/humascraper/.env/lib/python3.5/site-packages/play_scraper/utils.py", line 240, in parse_app_details
    icon = (soup.select_one('.dQrBL img.ujDFqe')
AttributeError: 'NoneType' object has no attribute 'attrs'
`

i used play-scraper 0.5.4 and i think google change googleplay html pages

**Comment by sajidrahman** [comment] 2019-05-05 20:54
Hi, I'm having this same error. I'm running play-scraper with Python 3, which was completely functional till last week.

**Comment by danieliu** [comment] 2019-05-11 17:07
Duplicate of #42

**Comment by danieliu** [comment] 2019-05-11 17:25
Fixed by #43

**Closed by danieliu** 2019-05-11 17:25 UTC
Labels: bug
